# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_07x_masterd_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_07x_masterd_service.proto',
  package='machinekit.masterd.service.test',
  serialized_pb='\n\x1etest_07x_masterd_service.proto\x12\x1fmachinekit.masterd.service.test\"\xb1\x01\n\x0bTestRequest\x12?\n\x04type\x18\n \x02(\x0e\x32\x31.machinekit.masterd.service.test.TestRequest.Type\x12\x0c\n\x04name\x18\x14 \x01(\t\x12\x10\n\x08strvalue\x18\x1e \x01(\t\x12\x10\n\x08intvalue\x18( \x01(\x05\x12\x11\n\tboolvalue\x18\x32 \x01(\x08\"\x1c\n\x04Type\x12\t\n\x05TEST1\x10\n\x12\t\n\x05TEST2\x10\x14\"\xb3\x01\n\tTestReply\x12=\n\x04type\x18\n \x02(\x0e\x32/.machinekit.masterd.service.test.TestReply.Type\x12\x0c\n\x04name\x18\x14 \x01(\t\x12\x10\n\x08strvalue\x18\x1e \x01(\t\x12\x10\n\x08intvalue\x18( \x01(\x05\x12\x11\n\tboolvalue\x18\x32 \x01(\x08\"\"\n\x04Type\x12\x0c\n\x08TEST1_OK\x10\n\x12\x0c\n\x08TEST2_OK\x10\x14')



_TESTREQUEST_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='machinekit.masterd.service.test.TestRequest.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEST1', index=0, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST2', index=1, number=20,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=217,
  serialized_end=245,
)

_TESTREPLY_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='machinekit.masterd.service.test.TestReply.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEST1_OK', index=0, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEST2_OK', index=1, number=20,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=393,
  serialized_end=427,
)


_TESTREQUEST = _descriptor.Descriptor(
  name='TestRequest',
  full_name='machinekit.masterd.service.test.TestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='machinekit.masterd.service.test.TestRequest.type', index=0,
      number=10, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='machinekit.masterd.service.test.TestRequest.name', index=1,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strvalue', full_name='machinekit.masterd.service.test.TestRequest.strvalue', index=2,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intvalue', full_name='machinekit.masterd.service.test.TestRequest.intvalue', index=3,
      number=40, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boolvalue', full_name='machinekit.masterd.service.test.TestRequest.boolvalue', index=4,
      number=50, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TESTREQUEST_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=245,
)


_TESTREPLY = _descriptor.Descriptor(
  name='TestReply',
  full_name='machinekit.masterd.service.test.TestReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='machinekit.masterd.service.test.TestReply.type', index=0,
      number=10, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=10,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='machinekit.masterd.service.test.TestReply.name', index=1,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strvalue', full_name='machinekit.masterd.service.test.TestReply.strvalue', index=2,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intvalue', full_name='machinekit.masterd.service.test.TestReply.intvalue', index=3,
      number=40, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boolvalue', full_name='machinekit.masterd.service.test.TestReply.boolvalue', index=4,
      number=50, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TESTREPLY_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=248,
  serialized_end=427,
)

_TESTREQUEST.fields_by_name['type'].enum_type = _TESTREQUEST_TYPE
_TESTREQUEST_TYPE.containing_type = _TESTREQUEST;
_TESTREPLY.fields_by_name['type'].enum_type = _TESTREPLY_TYPE
_TESTREPLY_TYPE.containing_type = _TESTREPLY;
DESCRIPTOR.message_types_by_name['TestRequest'] = _TESTREQUEST
DESCRIPTOR.message_types_by_name['TestReply'] = _TESTREPLY

class TestRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTREQUEST

  # @@protoc_insertion_point(class_scope:machinekit.masterd.service.test.TestRequest)

class TestReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTREPLY

  # @@protoc_insertion_point(class_scope:machinekit.masterd.service.test.TestReply)


# @@protoc_insertion_point(module_scope)
