/* config.h.in.  Generated from configure.ac by autoheader.  */

/********************************************************************
* Description: config.h
*
*	Common defines used in many emc2 source files.
*       To add to this file, edit Section 4 in configure.ac
*       and then run autoheader.
*
* Author: Autogenerated by autoheader
* License: LGPL Version 2
* System: Linux
*
* Copyright (c) 2004 All rights reserved.
********************************************************************/
#ifndef EMC2_CONFIG_H
#define EMC2_CONFIG_H

/* LINELEN is used throughout for buffer sizes, length of file name strings,
   etc. Let's just have one instead of a multitude of defines all the same. */
#define LINELEN 255
/* Used in a number of places for sprintf() buffers. */
#define BUFFERLEN 80

/* RTAPI array sizes */
#define RTAPI_MAX_MODULES	64
#define RTAPI_MAX_TASKS		64
#define RTAPI_MAX_SHMEMS	32

// default size of the HAL data segment
// can be overridden by the rtapi.so/ko module param hal_size=<n>
#define HAL_SIZE                262000

// default size of the thread stack size passed to rtapi_task_new()
// in hal_create_thread()
// can be overridden by an option to rtapi_msgd
#define HAL_STACKSIZE           32768

#if ! defined(THREAD_FLAVOR_ID)
// this isnt allowed when building RTAPI
#ifdef RTAPI
#error RTAPI defined but THREAD_FLAVOR_ID not defined
#endif
#elif THREAD_FLAVOR_ID == RTAPI_POSIX_ID
#  define RTAPI_POSIX
#  define THREAD_FLAVOR_NAME "posix"
#  define BUILD_SYS_USER_DSO
#  define THREADS_HEADERS "rtapi/rt-preempt.h"
#elif THREAD_FLAVOR_ID == RTAPI_RT_PREEMPT_ID
#  define RTAPI_RT_PREEMPT
#  define THREAD_FLAVOR_NAME "rt-preempt"
#  define BUILD_SYS_USER_DSO
#  define THREADS_HEADERS "rtapi/rt-preempt.h"
#elif THREAD_FLAVOR_ID == RTAPI_XENOMAI_ID
#  define RTAPI_XENOMAI
#  define THREAD_FLAVOR_NAME "xenomai"
#  define BUILD_SYS_USER_DSO
#  define THREADS_HEADERS "rtapi/xenomai.h"
#elif THREAD_FLAVOR_ID == RTAPI_XENOMAI_KERNEL_ID
#  define RTAPI_XENOMAI_KERNEL
#  define THREAD_FLAVOR_NAME "xenomai-kernel"
#  define BUILD_SYS_KBUILD
#  define THREADS_HEADERS "rtapi/xenomai-kernel.h"
#elif THREAD_FLAVOR_ID == RTAPI_RTAI_KERNEL_ID
#  define RTAPI_RTAI_KERNEL
#  define THREAD_FLAVOR_NAME "rtai-kernel"
#  define BUILD_SYS_KBUILD
#  define THREADS_HEADERS "rtapi/rtai-kernel.h"
#else
#error unknown value for THREAD_FLAVOR_ID
#endif



/* build hardware drivers */
#undef BUILD_DRIVERS

/* Directory for binaries */
#undef EMC2_BIN_DIR

/* Directory for po/mo translation files */
#undef EMC2_PO_DIR

/* Directory for ulapi shared objects */
#undef EMC2_RTLIB_DIR

/* Git version tag */
#define GIT_VERSION "unknown"

/* Define to 1 if you have the 'readline' library (-lreadline) and required
   headers */
#undef HAVE_READLINE

/* Define to 1 if linux/hidraw.h is usable and defines HIDIOCGRAWINFO */
#undef HIDRAW_H_USABLE

/* Define to 1 if asm/msr.h is usable and defines rdtscll */
#undef MSR_H_USABLE

/* Define to the address where bug reports for this package should be sent. */
#undef PACKAGE_BUGREPORT

/* Define to the full name of this package. */
#undef PACKAGE_NAME

/* Define to the full name and version of this package. */
#undef PACKAGE_STRING

/* Define to the one symbol short name of this package. */
#undef PACKAGE_TARNAME

/* Define to the home page for this package. */
#undef PACKAGE_URL

/* Define to the version of this package. */
#undef PACKAGE_VERSION

/* build for BeagleBone platform */
#undef TARGET_PLATFORM_BEAGLEBONE

/* build for Raspberry Pi platform */
#undef TARGET_PLATFORM_RASPBERRY

/* build PCI drivers with usermode PCI support */
#undef USERMODE_PCI

/* use ppdev ioctl instead of inb/outb */
#undef USE_PORTABLE_PARPORT_IO

/* Xenomai skin ('native' for v2, 'alchemy' for v3) */
#undef XENOMAI_SKIN

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE
#endif


#endif

